#!/bin/zsh

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

#autoload -U colors && colors
export CLICOLOR=1

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Colorful Man Pages
export PAGER=less
export LESS=-R
export LESS_TERMCAP_mb=$'\E[01;31m'         # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'    # begin bold
export LESS_TERMCAP_me=$'\E[0m'             # end mode
export LESS_TERMCAP_se=$'\E[0m'             # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'      # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'             # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m'   # begin underline

LOCAL="$HOME/.local/bin"

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export SUDO_ASKPASS="$LOCAL/dmenu/dmenupass"


if [ -x "/usr/bin/go" ]; then
  GOPATH="$HOME/.local/share/go"
fi

if [ -x "$HOME/lib/azure-cli/bin/az" ]; then
  AZ_BIN=$HOME/lib/azure-cli/bin
fi

if [ -x "$HOME/.fnm/fnm" ]; then
  FNM_PREFIX="$HOME/.fnm/node-versions/v15.5.1/installation"
  FNM_PACKAGES="$FNM_PREFIX/lib/node_modules/bin"
fi

if [ -d "$HOME/.asdf" ]; then
  ASDF_PREFIX="$HOME/.asdf/installs/nodejs/15.5.1"
  ASDF_PACKAGES="$ASDF_PREFIX/.npm/bin"
fi

if [ -x "~/.fzf.zsh" ]; then
  source ~/.fzf.zsh
  # Enable a better reverse search experience.
  export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
  export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --height=80% --color=dark"
fi

path=(
  "$LOCAL"
  "$LOCAL/dmenu"
  "$LOCAL/dwm"
  "$LOCAL/sb"
  "$LOCAL/statusbar"
  "$GOPATH"
  "$CONDA"
  "$AZ_BIN"
  # "$FNM_PACKAGES"
  "$ASDF_PACKAGES"
  "$path[@]"
)

export PATH
# export npm_config_prefix="$FNM_PREFIX/lib/node_modules"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/razak/.miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/razak/.miniconda/etc/profile.d/conda.sh" ]; then
        . "/home/razak/.miniconda/etc/profile.d/conda.sh"
    else
        export PATH="/home/razak/.miniconda/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# eval "$(fnm env)"
source $HOME/.oh-my-zsh/oh-my-zsh.sh
source $HOME/lib/azure-cli/az.completion
source $HOME/.asdf/asdf.sh
