#!/bin/zsh

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

#autoload -U colors && colors
export CLICOLOR=1

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Colorful Man Pages
export PAGER=less
export LESS=-R
export LESS_TERMCAP_mb=$'\E[01;31m'         # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'    # begin bold
export LESS_TERMCAP_me=$'\E[0m'             # end mode
export LESS_TERMCAP_se=$'\E[0m'             # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'      # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'             # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m'   # begin underline

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"

if [ -d "/home/razak/.oh-my-zsh" ]; then
  ZSH="/home/razak/.oh-my-zsh"
fi

if [ -x "/usr/bin/go" ]; then
  GOPATH="$HOME/.local/share/go"
fi

if [ -x "$HOME/lib/azure-cli/bin/az" ]; then
  AZ_BIN=$HOME/lib/azure-cli/bin
fi

if [ -x "$HOME/.fnm/fnm" ]; then
  FNMPATH="/home/razak/.fnm"
  FNM_PREFIX="$FNMPATH/node-versions/v15.5.1/installation"
  FNM_BIN="$FNM_PREFIX/bin"
  FNM_PACKAGES="$FNM_PREFIX/lib/node_modules/bin"
fi

LOCAL="$HOME/.local/bin"

path=(
  "$LOCAL"
  "$LOCAL/dmenu"
  "$LOCAL/dwm"
  "$LOCAL/sb"
  "$LOCAL/statusbar"
  "$GOPATH"
  "$AZ_BIN"
  "$FNMPATH"
  "$FNM_BIN"
  "$FNM_PACKAGES"
  "$path[@]"
)

export PATH
# export npm_config_prefix="$FNM_PREFIX/lib/node_modules"

if [ -x "~/.fzf.zsh" ]; then
  source ~/.fzf.zsh
  # Enable a better reverse search experience.
  export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
  export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --height=80% --color=dark"
fi

eval "$(fnm env)"
source $ZSH/oh-my-zsh.sh
source $HOME/lib/azure-cli/az.completion

# This is the list for lf icons:
export LF_ICONS="di=📁:\
fi=📃:\
tw=🤝:\
ow=📂:\
ln=⛓:\
or=❌:\
ex=🎯:\
*.txt=✍:\
*.mom=✍:\
*.me=✍:\
*.ms=✍:\
*.png=🖼:\
*.webp=🖼:\
*.ico=🖼:\
*.jpg=📸:\
*.jpe=📸:\
*.jpeg=📸:\
*.gif=🖼:\
*.svg=🗺:\
*.tif=🖼:\
*.tiff=🖼:\
*.xcf=🖌:\
*.html=🌎:\
*.xml=📰:\
*.gpg=🔒:\
*.css=🎨:\
*.pdf=📚:\
*.djvu=📚:\
*.epub=📚:\
*.csv=📓:\
*.xlsx=📓:\
*.tex=📜:\
*.md=📘:\
*.r=📊:\
*.R=📊:\
*.rmd=📊:\
*.Rmd=📊:\
*.m=📊:\
*.mp3=🎵:\
*.opus=🎵:\
*.ogg=🎵:\
*.m4a=🎵:\
*.flac=🎼:\
*.wav=🎼:\
*.mkv=🎥:\
*.mp4=🎥:\
*.webm=🎥:\
*.mpeg=🎥:\
*.avi=🎥:\
*.mov=🎥:\
*.mpg=🎥:\
*.wmv=🎥:\
*.m4b=🎥:\
*.flv=🎥:\
*.zip=📦:\
*.rar=📦:\
*.7z=📦:\
*.tar.gz=📦:\
*.z64=🎮:\
*.v64=🎮:\
*.n64=🎮:\
*.gba=🎮:\
*.nes=🎮:\
*.gdi=🎮:\
*.1=ℹ:\
*.nfo=ℹ:\
*.info=ℹ:\
*.log=📙:\
*.iso=📀:\
*.img=📀:\
*.bib=🎓:\
*.ged=👪:\
*.part=💔:\
*.torrent=🔽:\
*.jar=♨:\
*.java=♨:\
"
